{"name": "test_login_fail[测试用户名错误, 密码错误用户名:linux密码linux期望值{'code': 1004, 'msg': '用户名或密码错误', 'data': None}]", "status": "passed", "description": "测试用户名或密码错误", "steps": [{"name": "输入用户名", "status": "passed", "parameters": [{"name": "user", "value": "'linux'"}], "start": 1582701229454, "stop": 1582701229454}, {"name": "输入密码", "status": "passed", "parameters": [{"name": "pwd", "value": "'linux'"}], "start": 1582701229454, "stop": 1582701229454}], "parameters": [{"name": "data", "value": "{'case': '用户名错误, 密码错误', 'user': 'linux', 'pwd': 'linux', 'expected': {'code': 1004, 'msg': '用户名或密码错误', 'data': None}}"}], "start": 1582701229453, "stop": 1582701229454, "uuid": "44e02c27-f11c-4428-b559-a04dd72f33ae", "historyId": "9160a7ec7675d19ef99569abb22cfb91", "testCaseId": "23bc14a2becd8ad6fc8bdb5969b41867", "fullName": "test_allure_feature.TestLogin#test_login_fail", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "测试登录失败"}, {"name": "suite", "value": "test_allure_feature"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-1TP29R9"}, {"name": "thread", "value": "14420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_feature"}]}